# print('hello world!')
# print('The answer is ', 9+1, '.', sep='')
# print('hi', 'there', sep='\n')
# print('hi', end=' ')
# print('Brian')
# f = open('hello.txt', 'w')
# print("hi zach", file=f)
# ans = input('How are you?')
# print(ans)
# print('Glad you are ', ans, '.', sep='')
# print("I'm ok.")
# print(len(ans))
# print(max(90, 76, 69))
# print("I have", 10+10, "dollars")
# print(min(6, 17, 10, -1))
# print(abs(-45))
