# number1= int(input("Enter your first number"))
# number2= int(input("Enter your second number"))
# number3= int(input("Enter your third number"))
# print((number1*number2)/number3)
# number = int(input("pick a number"))
# print(number%2==0)
# money = int(input("Vacation Money"))
# print(money//1.17)
# name =(input("Name?"))
# print(ord(name[0]))